_target_: diffusion_planner.utils.optimizer.build_optimizer
learning_rate: 2.0e-4
weight_decay: 0.01
muon_momentum: 0.95
muon_nesterov: true
muon_ns_steps: 5
muon_eps: 1.0e-7
adamw_betas: [0.9, 0.999]
adamw_eps: 1.0e-8
verbose: true
