"""Model introspection tools that read a trained planner without changing it."""

from .attention import (
    AGENT_CLASS_NAMES,
    EMPTY_SLOT_NAME,
    UNLABELED_NAME,
    AttentionCapture,
    LayerAttention,
    SceneTokenLayout,
    capture_fusion_attention,
    class_summary,
    ego_query_attention,
    fusion_attention,
    fusion_dimensions,
    neighbor_classes,
    neighbor_valid,
    token_records,
)
from .closed_loop import RolloutStep, map_coverage_m, rollout
from .scene_edit import (
    DEFAULT_TIMESTEP_S,
    PlacedAgent,
    agent_history,
    edited_slots,
    free_slots,
    insert_agent,
    occupied_slots,
    read_agent,
    remove_agent,
    update_agent,
)
from .taxonomy import (
    BEARING_BUCKETS,
    BOUNDARY_BUCKETS,
    BOUNDARY_TYPE_NAMES,
    annotate_records,
    bearing_bucket,
    bucket_shares,
    lane_boundary_buckets,
    nearest_route_rank,
)
from .video import (
    FFMPEG_MISSING_MESSAGE,
    ffmpeg_available,
    write_frames,
    write_video,
)

__all__ = [
    "AGENT_CLASS_NAMES",
    "BEARING_BUCKETS",
    "BOUNDARY_BUCKETS",
    "BOUNDARY_TYPE_NAMES",
    "FFMPEG_MISSING_MESSAGE",
    "DEFAULT_TIMESTEP_S",
    "EMPTY_SLOT_NAME",
    "UNLABELED_NAME",
    "AttentionCapture",
    "LayerAttention",
    "RolloutStep",
    "PlacedAgent",
    "SceneTokenLayout",
    "agent_history",
    "annotate_records",
    "bearing_bucket",
    "bucket_shares",
    "capture_fusion_attention",
    "class_summary",
    "edited_slots",
    "ffmpeg_available",
    "ego_query_attention",
    "free_slots",
    "fusion_attention",
    "fusion_dimensions",
    "insert_agent",
    "lane_boundary_buckets",
    "map_coverage_m",
    "neighbor_classes",
    "neighbor_valid",
    "nearest_route_rank",
    "occupied_slots",
    "read_agent",
    "remove_agent",
    "rollout",
    "token_records",
    "update_agent",
    "write_frames",
    "write_video",
]
