class PipelineError(Exception): ...


class EncodingError(PipelineError): ...


class SidecarError(PipelineError): ...


class SourceChangedError(PipelineError): ...


class VersionExistsError(PipelineError): ...


class KeysetMismatchError(PipelineError): ...


class PlanError(PipelineError): ...


class IntegrityError(PipelineError): ...


class RuleMismatchError(PipelineError): ...
