class PipelineError(Exception): ...


class EncodingError(PipelineError): ...


class SidecarError(PipelineError): ...


class SourceChangedError(PipelineError): ...


class VersionExistsError(PipelineError): ...


class KeysetMismatchError(PipelineError): ...


class PlanError(PipelineError): ...


class IntegrityError(PipelineError): ...


class RuleMismatchError(PipelineError): ...


class PackWorkerError(PipelineError):
    """A pack worker raised or died. Carries the partition id where one is knowable."""
